---
# tasks file for fmarinetti.swarm-slave
- name: cleanup swarm config
  command: "docker swarm leave --force"
  register: output
  ignore_errors: true
  changed_when: output.rc == 0

- name: "join slave {{ inventory_hostname }} to swarm"
  command: "docker swarm join --token {{ token }} {{ manager_ipaddress }}:{{ manager_port }}"
  register: output
  changed_when: output.rc == 0
